version: '3'
services:
  mongodb:
        image: centos/mongodb-34-centos7
        container_name: "mongodb"
        environment:
          - MONGODB_USER=user
          - MONGODB_PASSWORD=password
          - MONGODB_ADMIN_PASSWORD=password
          - MONGODB_DATABASE=showcase
        ports:
            - 27017:27017
  keycloak:
    image: jboss/keycloak:3.4.3.Final
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: ovp-admin
      KEYCLOAK_PASSWORD: ovp-admin