version: '3'
services:
  # Mosca is a simple MQTT Broker
  # In OpenShift/Production we would use the Red Hat AMQ broker
  mosca:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883" # MQTT